Add 4.00 runtime. Multiple runtime managment.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -41,6 +41,7 @@ function remove_trailing_slash () {
 
 ###
 
+cd $(dirname "$0")
 mkdir -p bin etc dist
 
 ###
@@ -58,12 +59,34 @@ check_command "gcc"
 
 ###
 
+OCAML_VERSION=$(ocamlc -version | cut -c1-4)
+DEFAULT_RUNTIME_VERSION=''
+RUNTIME_VERSIONS=''
+for d in runtime/ocamlcc-byterun-?.??; do
+    V="${d:24:4}"
+    RUNTIME_VERSIONS="$RUNTIME_VERSIONS $V"
+    if [ "$OCAML_VERSION" = "$V" ]; then
+        DEFAULT_RUNTIME_VERSION="$OCAML_VERSION"
+    fi
+done
+if [ "$OCAML_VERSION" != "$DEFAULT_RUNTIME_VERSION" ]; then
+    echo "Error: Incompatible OCaml version: $OCAML_VERSION" 1>&2
+    echo "       Supported versions: $RUNTIME_VERSIONS" 1>&2
+    exit 1
+fi
+RUNTIME_VERSION_LIST='['
+for v in $RUNTIME_VERSIONS; do
+    RUNTIME_VERSION_LIST="$RUNTIME_VERSION_LIST \"$v\";"
+done
+RUNTIME_VERSION_LIST="$RUNTIME_VERSION_LIST ]"
+
+###
+
 OCAMLBUILD=$(which ocamlbuild)
 OCAMLLIB=$(ocamlc -where)
 GCC=$(which gcc)
 ARCH=$(test -x /bin/uname && /bin/uname -m || echo none)
 VERSION=$(cat VERSION)
-RUNTIME_VERSION=$(cat runtime/VERSION)
 SAVED_PWD=$(pwd)
 
 ###
@@ -147,13 +170,16 @@ fi
 ###
 
 echo "\
+SHELL = bash
+
 INSTALL_OCAMLCLEAN = $INSTALL_OCAMLCLEAN
 OCAMLCLEAN = $OCAMLCLEAN
 OCAMLCLEAN_VERSION = $OCAMLCLEAN_VERSION
 OCAMLCLEAN_DIRECTORY = $OCAMLCLEAN_DIRECTORY
 OCAMLCLEAN_ARCHIVE = $OCAMLCLEAN_ARCHIVE
 VERSION = $VERSION
-RUNTIME_VERSION = $RUNTIME_VERSION
+RUNTIME_VERSIONS = $RUNTIME_VERSIONS
+DEFAULT_RUNTIME_VERSION = $DEFAULT_RUNTIME_VERSION
 
 OCAMLBUILD = $OCAMLBUILD -cflags -w,Ae,-warn-error,A -lflags -w,Ae,-warn-error,A -no-links -classic-display
 
@@ -167,7 +193,8 @@ MAN1DIR = $MANDIR/man1
 echo "\
 (* Generated by configure *)
 let version = \"$VERSION\";;
-let runtime_version = \"$RUNTIME_VERSION\";;
+let runtime_versions = $RUNTIME_VERSION_LIST;;
+let default_runtime_version = \"$DEFAULT_RUNTIME_VERSION\";;
 let include_dir = \"$INCLUDEDIR/ocamlcc\";;
 let default_arch = \"gen\";;
 let ccomp = \"$CCOMP\";;
